// Application Actions

export const FETCH_SMURFS_START = 'FETCH_SMURFS_START';
export const FETCH_SMURFS_FINISH = 'FETCH_SMURFS_FINISH';

export const FETCH_SMURFS_RECEIVED = 'FETCH_SMURFS_RECEIVED';
export const FETCH_SMURFS_FAIL = 'FETCH_SETS_FAIL';
